from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Encrypt(object):
    def setupUi(self, Encrypt):
        Encrypt.setObjectName("Encrypt")
        Encrypt.resize(880, 464)
        self.pushButton = QtWidgets.QPushButton(Encrypt)
        self.pushButton.setGeometry(QtCore.QRect(370, 390, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Encrypt)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 881, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(133, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Encrypt)
        self.label_2.setGeometry(QtCore.QRect(120, 150, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Encrypt)
        self.lineEdit.setGeometry(QtCore.QRect(210, 160, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(Encrypt)
        self.comboBox.setGeometry(QtCore.QRect(370, 260, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Encrypt)
        QtCore.QMetaObject.connectSlotsByName(Encrypt)

    def retranslateUi(self, Encrypt):
        _translate = QtCore.QCoreApplication.translate
        Encrypt.setWindowTitle(_translate("Encrypt", "Encrypt"))
        self.pushButton.setText(_translate("Encrypt", "Encrypt"))
        self.label.setText(_translate(
            "Encrypt", "Hashlib Wizard Cryptography"))
        self.label_2.setText(_translate("Encrypt", "Text:"))
        self.comboBox.setItemText(0, _translate("Encrypt", "Sha1"))
        self.comboBox.setItemText(1, _translate("Encrypt", "Sha224"))
        self.comboBox.setItemText(2, _translate("Encrypt", "Sha256"))
        self.comboBox.setItemText(3, _translate("Encrypt", "Sha384"))
        self.comboBox.setItemText(4, _translate("Encrypt", "Sha512"))
